task1: main.o
	
	gcc -g -O0 -o task1 main.o
 


main.o: main.c
	
	gcc -g -O0 -c main.c
 


clean:
	
	rm task1 *.o


indent:
	
	indent -kr -nut -ts4 main.c


install:
	install ./task1 /usr/local/bin

uninstall:
	rm -rf /usr/local/bin/task1

dist: $(SRCS) $(AUX)
	Команды

$(cat test1 > result)
$(cat test1 >> result)